language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
  include:
    - os: linux
      dist: bionic

    - os: linux
      dist: xenial

    - os: linux
      dist: trusty

#    Exclude linux/precise: "#error "unsupported GCC version" (gcc 4.6.3)
#    - os: linux
#      dist: precise

    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.6

    - os: osx
      osx_image: xcode11.5

    - os: osx
      osx_image: xcode11.4

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode11.2

    - os: osx
      osx_image: xcode11.1

    - os: osx
      osx_image: xcode11

    - os: osx
      osx_image: xcode10.3

    - os: osx
      osx_image: xcode10.2

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode10

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode9.3

    - os: osx
      osx_image: xcode9.2

    - os: osx
      osx_image: xcode9.1

    - os: osx
      osx_image: xcode9

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode7.3


script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
