image:
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  # Exclude unsupported "Visual Studio 2013": error C2143: syntax error : missing ';' before 'user-defined conversion'
  #- Visual Studio 2013

build_script:
- cmd: |-
    mkdir build
    cd build
    cmake ..
    cmake --build .
